server:
  port: 8080
  servlet:
    context-path: /gencode
spring:
  application:
    name: td-generator
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dev_td_db?useUnicode=true&characterEncoding=utf8
      username: root
      password: tudedong
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      minIdle: 1
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      validation-query: select 1.txt
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      max-active: 20
      max-wait: 60000
      initial-size: 1
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.td.generator
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
output: D:/IdeaProjects/generator-main/gencode/
templatePath: D:\IdeaProjects\generator-main\td-generator\src\main\resources\tmpcode